repos:
  - repo: local
    hooks:
      - id: uv-lock-check
        name: uv => make sure the lock file is up-to-date
        stages: [pre-commit]
        language: system
        entry: uv lock --locked
        always_run: true
        pass_filenames: false
      - id: ty
        name: ty => type checking
        stages: [pre-commit]
        language: system
        entry: uv run ty check
        always_run: true
        pass_filenames: false
      - id: ruff-formatting
        name: ruff => code formatting
        stages: [pre-commit]
        language: system
        entry: uv run ruff format
        always_run: true
        pass_filenames: false
      - id: ruff-linting
        name: ruff => linting
        stages: [pre-commit]
        language: system
        entry: uv run ruff check .
        always_run: true
        pass_filenames: false
      - id: prettier-formatting
        name: prettier => code formatting
        stages: [pre-commit]
        language: system
        entry: npx prettier --write src
        always_run: true
        pass_filenames: false
      - id: documentation-formatting
        name: markdownlint => markdown formatting
        stages: [pre-commit]
        language: system
        entry: markdownlint --fix docs --disable MD013
        always_run: true
        pass_filenames: false
      - id: pytest fast
        name: pytest => fast tests
        stages: [pre-commit]
        language: system
        entry: uv run pytest -m fast
        always_run: true
        pass_filenames: false
      - id: sqlfluff-linting
        name: sqlfluff => SQL linting
        stages: [pre-push]
        language: system
        entry: uv run sqlfluff lint .
        always_run: true
        pass_filenames: false
      - id: sqlfluff-formatting
        name: sqlfluff => SQL formatting
        stages: [pre-push]
        language: system
        entry: uv run sqlfluff format .
        always_run: true
        pass_filenames: false
      - id: pip-audit
        name: pip-audit => vulnerability checking
        stages: [pre-push]
        language: system
        entry: uv run pip-audit --ignore-vuln GHSA-c33w-24p9-8m24
        always_run: true
        pass_filenames: false
      - id: pytest
        name: pytest => testing
        stages: [pre-push]
        language: system
        entry: uv run pytest --cov -m "not teradata"
        always_run: true
        pass_filenames: false
      - id: coverage
        name: coverage => testing coverage
        stages: [pre-push]
        language: system
        entry: uv run coverage report -m
        always_run: true
        pass_filenames: false
