site_name: App An치lisis Siniestralidad
site_author: Gerencia de Modelacion Tecnica

repo_url: https://github.com/sebastobone/app-analisis-siniestralidad

nav:
  - Introducci칩n: index.md
  - Instalaci칩n: instalacion.md
  - Configuraci칩n: configuracion.md
  - Uso de la plantilla: uso.md

theme:
  name: material
  palette:
    accent: cyan
    scheme: slate
  language: es
  features:
    - content.code.copy
    - content.code.select
    - content.tabs.link

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
