site_name: App Análisis Siniestralidad
site_author: Gerencia de Modelacion Tecnica

repo_url: https://github.com/sebastobone/app-analisis-siniestralidad

nav:
  - Introducción: index.md
  - Instalación: instalacion.md
  - Estructura: estructura.md
  - Configuración:
    - Fuentes de información y permisos: config/fuentes.md
    - Consultas: config/queries.md
    - Definición de aperturas: config/aperturas.md
    - Actualización de estados financieros (SAP): config/sap.md
    - Cuadre contable: config/cuadre_contable.md
  - Uso:
    - Inicio: uso/inicio.md
    - Ingreso de parámetros: uso/parametros.md
    - Extracción de información: uso/extraccion.md
    - Generación de controles: uso/controles.md
    - Descripción de la plantilla: uso/plantilla.md
    - Funciones de la plantilla: uso/funciones_plantilla.md
    - Análisis de triángulos: uso/triangulos.md
    - Análisis de entremés: uso/entremes.md
    - Consolidación de resultados: uso/resultados.md
    - Generación de informes: uso/informes.md
  - Actualización: actualizacion.md
  - Diccionario: diccionario.md
  - Particularidades por negocio:
    - SOAT: particularidades/soat.md

theme:
  name: material
  palette:
    accent: cyan
    scheme: slate
  language: es
  features:
    - content.code.copy
    - content.code.select
    - content.tabs.link

plugins:
  - include-markdown

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
