[project]
name = "plantilla-seguimiento"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.5"
dependencies = [
    "fastexcel>=0.12.0",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "polars>=1.14.0",
    "pyautogui>=0.9.54",
    "pytest>=8.3.4",
    "teradatasql>=20.0.0.20",
    "tqdm>=4.67.1",
    "xlsxwriter>=3.2.0",
    "xlwings>=0.33.3",
]
