[project]
name = "plantilla-seguimiento"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.5"
dependencies = [
    "pandas>=2.2.3",
    "polars>=1.14.0",
    "xlwings>=0.33.3",
]
